/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:TelaCarregar[MAX_PLAYERS][3];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	TelaCarregar[playerid][0] = CreatePlayerTextDraw(playerid, 225.000000, 122.000000, "Zona_Oeste");
	PlayerTextDrawFont(playerid, TelaCarregar[playerid][0], 0);
	PlayerTextDrawLetterSize(playerid, TelaCarregar[playerid][0], 1.474995, 8.350009);
	PlayerTextDrawTextSize(playerid, TelaCarregar[playerid][0], 401.000000, 23.500000);
	PlayerTextDrawSetOutline(playerid, TelaCarregar[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, TelaCarregar[playerid][0], 4);
	PlayerTextDrawAlignment(playerid, TelaCarregar[playerid][0], 1);
	PlayerTextDrawColor(playerid, TelaCarregar[playerid][0], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, TelaCarregar[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, TelaCarregar[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, TelaCarregar[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, TelaCarregar[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, TelaCarregar[playerid][0], 0);

	TelaCarregar[playerid][1] = CreatePlayerTextDraw(playerid, 267.000000, 185.000000, "Roleplay");
	PlayerTextDrawFont(playerid, TelaCarregar[playerid][1], 0);
	PlayerTextDrawLetterSize(playerid, TelaCarregar[playerid][1], 1.299993, 7.000004);
	PlayerTextDrawTextSize(playerid, TelaCarregar[playerid][1], 401.000000, 23.500000);
	PlayerTextDrawSetOutline(playerid, TelaCarregar[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, TelaCarregar[playerid][1], 4);
	PlayerTextDrawAlignment(playerid, TelaCarregar[playerid][1], 1);
	PlayerTextDrawColor(playerid, TelaCarregar[playerid][1], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, TelaCarregar[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, TelaCarregar[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, TelaCarregar[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, TelaCarregar[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, TelaCarregar[playerid][1], 0);

	TelaCarregar[playerid][2] = CreatePlayerTextDraw(playerid, 271.000000, 256.000000, "abre.ai/zonaoesterp_____________2023");
	PlayerTextDrawFont(playerid, TelaCarregar[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, TelaCarregar[playerid][2], 0.170827, 1.050004);
	PlayerTextDrawTextSize(playerid, TelaCarregar[playerid][2], 379.000000, 22.500000);
	PlayerTextDrawSetOutline(playerid, TelaCarregar[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, TelaCarregar[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, TelaCarregar[playerid][2], 1);
	PlayerTextDrawColor(playerid, TelaCarregar[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, TelaCarregar[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, TelaCarregar[playerid][2], 20);
	PlayerTextDrawUseBox(playerid, TelaCarregar[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, TelaCarregar[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, TelaCarregar[playerid][2], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, TelaCarregar[playerid][0]);
	PlayerTextDrawDestroy(playerid, TelaCarregar[playerid][1]);
	PlayerTextDrawDestroy(playerid, TelaCarregar[playerid][2]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, TelaCarregar[playerid][0]);
		PlayerTextDrawShow(playerid, TelaCarregar[playerid][1]);
		PlayerTextDrawShow(playerid, TelaCarregar[playerid][2]);
		return 1;
	}
	return 0;
}
